name: landing_page_sai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.9 # Tambahkan dependensi url_launcher di sini
  google_fonts: ^6.2.1
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/a.png
    - assets/b.png
    - assets/c.png
    - assets/d.png
    - assets/e.png
